import json
import os
from typing import List, Dict, Any
# from langchain_openai import ChatOpenAI
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from src.state import AgentState, JudicialOpinion, Evidence

# Load rubric to know what we are judging
RUBRIC_PATH = os.path.join(os.getcwd(), "rubric.json")
with open(RUBRIC_PATH, "r") as f:
    RUBRIC = json.load(f)

llm = ChatOllama(
    model="gpt-oss:120b-cloud",
    base_url="https://ollama.com"
)

def get_judicial_opinion(
    judge_persona: str, 
    persona_name: str, 
    criterion: Dict[str, Any], 
    evidence_list: List[Evidence]
) -> JudicialOpinion:
    """
    Helper function to invoke the LLM for a specific judge and criterion.
    Uses .bind_tools() to force structured output via tool/function calling.
    """
    # Bind the Pydantic model as a tool
    llm_with_tools = llm.bind_tools([JudicialOpinion])
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", f"{judge_persona}\n\n"
                   "You are an expert auditor. You MUST use the 'JudicialOpinion' tool to provide your evaluation. "
                   "Do not provide a text response; ONLY use the tool."),
        ("human", "Rubric Criterion: {criterion_name}\n"
                  "Success Pattern: {success_pattern}\n"
                  "Failure Pattern: {failure_pattern}\n\n"
                  "Forensic Evidence Collected:\n{evidence_text}\n\n"
                  "Evaluate this criterion using the JudicialOpinion tool.")
    ])
    
    # Format evidence for the prompt
    evidence_text = ""
    for idx, e in enumerate(evidence_list):
        evidence_text += f"Evidence [{idx}] ({e.location}): {e.rationale}\nContent snippet: {e.content}\n\n"
    
    if not evidence_text:
        evidence_text = "No specific forensic evidence was collected for this criterion."

    # Create the chain
    chain = prompt | llm_with_tools
    
    # Invoke
    response = chain.invoke({
        "criterion_name": criterion["name"],
        "success_pattern": criterion["success_pattern"],
        "failure_pattern": criterion["failure_pattern"],
        "evidence_text": evidence_text
    })
    
    # Extract and Coerce the tool call
    if response.tool_calls:
        tool_call = response.tool_calls[0]
        args = tool_call["args"]
        
        # 1. Coerce Score (Clip to 1-5)
        raw_score = args.get("score", 1)
        try:
            score = int(raw_score)
            score = max(1, min(5, score))
        except (ValueError, TypeError):
            score = 1
            
        # 2. Coerce Judge Name
        # The model might return "TechLead Auditor" or "The Prosecutor"
        raw_judge = args.get("judge", persona_name)
        judge = persona_name # Default to the intended persona
        if "prosecutor" in str(raw_judge).lower():
            judge = "Prosecutor"
        elif "defense" in str(raw_judge).lower():
            judge = "Defense"
        elif "tech" in str(raw_judge).lower():
            judge = "TechLead"

        # 3. Coerce Cited Evidence (List[str])
        raw_evidence = args.get("cited_evidence", [])
        cited_evidence = []
        if isinstance(raw_evidence, list):
            for e in raw_evidence:
                if isinstance(e, dict):
                    # Extract a string from the dict if the model was too smart
                    cited_evidence.append(str(e.get("content") or e.get("location") or str(e)))
                else:
                    cited_evidence.append(str(e))
        else:
            cited_evidence = [str(raw_evidence)]

        opinion = JudicialOpinion(
            judge=judge,
            criterion_id=criterion["id"],
            score=score,
            argument=str(args.get("argument", "No argument provided.")),
            cited_evidence=cited_evidence
        )
    else:
        # Fallback if no tool call
        print(f"Warning: No tool call generated by {persona_name}.")
        opinion = JudicialOpinion(
            judge=persona_name,
            criterion_id=criterion["id"],
            score=1,
            argument=f"Error: Judge failed to provide a structured opinion. Output: {response.content[:100]}",
            cited_evidence=[]
        )
    
    # Final metadata check
    opinion.judge = persona_name
    opinion.criterion_id = criterion["id"]
    return opinion

def prosecutor_node(state: AgentState) -> Dict[str, Any]:
    """
    Prosecutor: Cynical, detail-oriented, looks for missing pieces.
    """
    print("--- Prosecutor is scrutinizing the evidence ---")
    persona = ("You are a cynical, detail-oriented prosecutor. Your job is to "
               "assume the developer cut corners. Scrutinize the Evidence for absence. "
               "If a file exists but is incomplete, argue for a low score. "
               "Your core question: 'What is missing?'.")
    
    new_opinions = []
    evidences = state.get("evidences", {})
    
    for dim in RUBRIC["dimensions"]:
        criterion_id = dim["id"]
        evidence_list = evidences.get(criterion_id, [])
        opinion = get_judicial_opinion(persona, "Prosecutor", dim, evidence_list)
        new_opinions.append(opinion)
        
    return {"opinions": new_opinions}

def defense_node(state: AgentState) -> Dict[str, Any]:
    """
    Defense: Empathetic, assumes good intent, highlights clever workarounds.
    """
    print("--- Defense is building the case for the developer ---")
    persona = ("You are an empathetic defense attorney. Your job is to assume "
               "good intent and look for the 'spirit of the law.' Highlight clever workarounds and "
               "effort. If a component is partially implemented, argue for partial credit. "
               "Your core question: 'What was attempted, and what can be learned from it?'.")
    
    new_opinions = []
    evidences = state.get("evidences", {})
    
    for dim in RUBRIC["dimensions"]:
        criterion_id = dim["id"]
        evidence_list = evidences.get(criterion_id, [])
        opinion = get_judicial_opinion(persona, "Defense", dim, evidence_list)
        new_opinions.append(opinion)
        
    return {"opinions": new_opinions}

def tech_lead_node(state: AgentState) -> Dict[str, Any]:
    """
    Tech Lead: Pragmatic, cares about maintainability and architecture. Tie-breaker.
    """
    print("--- Tech Lead is evaluating architectural soundness ---")
    persona = ("You are a pragmatic Tech Lead. You don't care about intent "
               "or cynicism. You only care about the artifacts. Is the code maintainable? "
               "Does the architecture actually solve the problem? You are the tie-breaker.")
    
    new_opinions = []
    evidences = state.get("evidences", {})
    
    for dim in RUBRIC["dimensions"]:
        criterion_id = dim["id"]
        evidence_list = evidences.get(criterion_id, [])
        opinion = get_judicial_opinion(persona, "TechLead", dim, evidence_list)
        new_opinions.append(opinion)
        
    return {"opinions": new_opinions}
